spring.datasource.url=jdbc:postgresql://localhost:5433/xantares_db
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate: ????????????? ???????/????????? ??????? ?? ?????? ????? ??????? ? entity
spring.jpa.hibernate.ddl-auto=update

# ????????? ?????? SQL ??????? ? ??????? (????? ??????? ??? ????????)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true